# RabbitMQ connection
spring.rabbitmq.host=0.0.0.0
spring.rabbitmq.port=5678
spring.rabbitmq.username=student
spring.rabbitmq.password=student

# Exchange si routing key originale
sqliteexample.rabbitmq.exchange=sqliteexample.direct
sqliteexample.rabbitmq.routingkey=sqliteexample.routingkey1
sqliteexample.rabbitmq.queue=sqliteexample.queue

# Queue-uri pentru microservicii
gateway.queue=queue.gateway
create.queue=queue.create
read.queue=queue.read
update.queue=queue.update
delete.queue=queue.delete

# SQLite datasource
spring.datasource.url=jdbc:sqlite:beers.db
spring.datasource.driver-class-name=org.sqlite.JDBC